@startuml

class Reactor {
    Poller poller
    Dispatch dispatch
    Selector selector
}

class Acceptor
class Poller
interface Dispatch
class MultiThreadDispatch implements Dispatch

class SocketProcessor

Reactor *.. Poller
Reactor *.. Dispatch
Acceptor *.. Reactor

MultiThreadDispatch *.. SocketProcessor

@enduml