@startuml

class Reactor {
    - Poller poller
    - Dispatch dispatch
    - Selector selector
}

class Acceptor
class Poller
interface Dispatch
class MultiThreadDispatch implements Dispatch

class SocketProcessor

Reactor *.. "1" Poller
Reactor *.. "1" Dispatch
Reactor *.. "1" Acceptor

MultiThreadDispatch *.. "n" SocketProcessor

@enduml